server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: case-execute-service

# 日志配置
logging:
  level:
    com.caseexecute: debug
    org.springframework.web: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"

# 文件上传配置
file:
  upload:
    # 上传文件存储路径
    path: /tmp/case-execute/uploads/
    # 最大文件大小
    max-size: 100MB
    # 允许的文件类型
    allowed-types: .zip,.xlsx,.xls,.py,.txt

# 用例执行配置
case:
  execution:
    # 单个用例执行超时时长（分钟），默认5分钟
    timeout-minutes: 5
    # 日志输出配置
    log:
      # 是否启用实时日志输出到控制台
      enable-real-time-console-output: true
      # 是否启用日志文件输出
      enable-file-output: true
      # 日志输出级别过滤（INFO, DEBUG, WARN, ERROR）
      log-level: INFO
      # 是否显示时间戳
      show-timestamp: true
      # 是否显示用例信息前缀
      show-test-case-prefix: true

# gohttpserver配置
gohttpserver:
  url: http://localhost:8081
